---
apiVersion: v1
kind: Service
metadata:
  name: postgre
  namespace: postgre
  labels:
    app: postgresql
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      name: postgre
  type: ClusterIP
  internalTrafficPolicy: Cluster
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack